# Generated by Django 5.0.2 on 2024-03-02 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condominio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('number_of_dwellings', models.PositiveIntegerField()),
                ('year_of_construction', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'Condominios',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('age', models.PositiveBigIntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=100)),
                ('charge', models.CharField(max_length=100)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('phone_number', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Empleados',
            },
        ),
        migrations.CreateModel(
            name='RoleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'RoleType',
            },
        ),
        migrations.CreateModel(
            name='Directivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=40)),
                ('acess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='condominioApp.roletype')),
            ],
            options={
                'db_table': 'Directivos',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=40)),
                ('acess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='condominioApp.roletype')),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='condominioApp.condominio')),
            ],
            options={
                'db_table': 'Users',
            },
        ),
    ]
