# Generated by Django 5.0.2 on 2024-03-04 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominioApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edificios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloque', models.CharField(max_length=50, unique=True)),
                ('year_construction', models.CharField(max_length=30)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='condominioApp.condominio')),
            ],
            options={
                'db_table': 'Edificios',
            },
        ),
    ]
