# Generated by Django 5.0.2 on 2024-03-06 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominioApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_pago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField(blank=True)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='condominioApp.condominio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='condominioApp.users')),
            ],
            options={
                'db_table': 'Mantenimiento',
            },
        ),
    ]
