# Generated by Django 5.0.2 on 2024-03-02 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('condominioApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condominio',
            name='year_of_construction',
        ),
    ]
