# Generated by Django 5.0.2 on 2024-03-04 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominioApp', '0002_edificios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_dpto', models.PositiveBigIntegerField()),
                ('telefono_casa', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('edificios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='condominioApp.edificios')),
                ('usuarios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='condominioApp.users')),
            ],
            options={
                'db_table': 'Departamentos',
            },
        ),
    ]
