# Generated by Django 5.0.2 on 2024-03-03 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominioApp', '0003_condominio_year_construction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directivo',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
